/**
 * ISO 3166-1 alpha-2 country codes → country names (Portuguese).
 * Used for auto-filling country from UN/LOCODE port code (first 2 chars).
 * @see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
 */
export const COUNTRY_CODE_TO_NAME: Record<string, string> = {
  AD: 'Andorra',
  AE: 'Emirados Árabes Unidos',
  AF: 'Afeganistão',
  AG: 'Antígua e Barbuda',
  AL: 'Albânia',
  AM: 'Armênia',
  AO: 'Angola',
  AR: 'Argentina',
  AT: 'Áustria',
  AU: 'Austrália',
  AZ: 'Azerbaijão',
  BA: 'Bósnia e Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Bélgica',
  BF: 'Burkina Faso',
  BG: 'Bulgária',
  BH: 'Bahrein',
  BI: 'Burundi',
  BJ: 'Benim',
  BN: 'Brunei',
  BO: 'Bolívia',
  BR: 'Brasil',
  BS: 'Bahamas',
  BT: 'Butão',
  BW: 'Botsuana',
  BY: 'Bielorrússia',
  BZ: 'Belize',
  CA: 'Canadá',
  CD: 'República Democrática do Congo',
  CF: 'República Centro-Africana',
  CG: 'República do Congo',
  CH: 'Suíça',
  CI: 'Costa do Marfim',
  CL: 'Chile',
  CM: 'Camarões',
  CN: 'China',
  CO: 'Colômbia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cabo Verde',
  CY: 'Chipre',
  CZ: 'República Tcheca',
  DE: 'Alemanha',
  DJ: 'Djibuti',
  DK: 'Dinamarca',
  DO: 'República Dominicana',
  DZ: 'Argélia',
  EC: 'Equador',
  EE: 'Estônia',
  EG: 'Egito',
  ER: 'Eritreia',
  ES: 'Espanha',
  ET: 'Etiópia',
  FI: 'Finlândia',
  FJ: 'Fiji',
  FM: 'Micronésia',
  FR: 'França',
  GA: 'Gabão',
  GB: 'Reino Unido',
  GD: 'Granada',
  GE: 'Geórgia',
  GH: 'Gana',
  GM: 'Gâmbia',
  GN: 'Guiné',
  GQ: 'Guiné Equatorial',
  GR: 'Grécia',
  GT: 'Guatemala',
  GW: 'Guiné-Bissau',
  GY: 'Guiana',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croácia',
  HT: 'Haiti',
  HU: 'Hungria',
  ID: 'Indonésia',
  IE: 'Irlanda',
  IL: 'Israel',
  IN: 'Índia',
  IQ: 'Iraque',
  IR: 'Irã',
  IS: 'Islândia',
  IT: 'Itália',
  JM: 'Jamaica',
  JO: 'Jordânia',
  JP: 'Japão',
  KE: 'Quênia',
  KG: 'Quirguistão',
  KH: 'Camboja',
  KI: 'Kiribati',
  KM: 'Comores',
  KN: 'São Cristóvão e Névis',
  KP: 'Coreia do Norte',
  KR: 'Coreia do Sul',
  KW: 'Kuwait',
  KZ: 'Cazaquistão',
  LA: 'Laos',
  LB: 'Líbano',
  LC: 'Santa Lúcia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Libéria',
  LS: 'Lesoto',
  LT: 'Lituânia',
  LU: 'Luxemburgo',
  LV: 'Letônia',
  LY: 'Líbia',
  MA: 'Marrocos',
  MC: 'Mônaco',
  MD: 'Moldávia',
  ME: 'Montenegro',
  MG: 'Madagascar',
  MH: 'Ilhas Marshall',
  MK: 'Macedônia do Norte',
  ML: 'Mali',
  MM: 'Mianmar',
  MN: 'Mongólia',
  MO: 'Macau',
  MR: 'Mauritânia',
  MT: 'Malta',
  MU: 'Maurícia',
  MV: 'Maldivas',
  MW: 'Malawi',
  MX: 'México',
  MY: 'Malásia',
  MZ: 'Moçambique',
  NA: 'Namíbia',
  NE: 'Níger',
  NG: 'Nigéria',
  NI: 'Nicarágua',
  NL: 'Países Baixos',
  NO: 'Noruega',
  NP: 'Nepal',
  NR: 'Nauru',
  NZ: 'Nova Zelândia',
  OM: 'Omã',
  PA: 'Panamá',
  PE: 'Peru',
  PG: 'Papua-Nova Guiné',
  PH: 'Filipinas',
  PK: 'Paquistão',
  PL: 'Polônia',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguai',
  QA: 'Catar',
  RO: 'Romênia',
  RS: 'Sérvia',
  RU: 'Rússia',
  RW: 'Ruanda',
  SA: 'Arábia Saudita',
  SB: 'Ilhas Salomão',
  SC: 'Seicheles',
  SD: 'Sudão',
  SE: 'Suécia',
  SG: 'Singapura',
  SI: 'Eslovênia',
  SK: 'Eslováquia',
  SL: 'Serra Leoa',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somália',
  SR: 'Suriname',
  SS: 'Sudão do Sul',
  ST: 'São Tomé e Príncipe',
  SV: 'El Salvador',
  SY: 'Síria',
  SZ: 'Essuatíni',
  TD: 'Chade',
  TG: 'Togo',
  TH: 'Tailândia',
  TJ: 'Tajiquistão',
  TL: 'Timor-Leste',
  TM: 'Turcomenistão',
  TN: 'Tunísia',
  TO: 'Tonga',
  TR: 'Turquia',
  TT: 'Trinidad e Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TZ: 'Tanzânia',
  UA: 'Ucrânia',
  UG: 'Uganda',
  US: 'Estados Unidos',
  UY: 'Uruguai',
  UZ: 'Uzbequistão',
  VA: 'Vaticano',
  VC: 'São Vicente e Granadinas',
  VE: 'Venezuela',
  VN: 'Vietnã',
  VU: 'Vanuatu',
  WS: 'Samoa',
  YE: 'Iêmen',
  ZA: 'África do Sul',
  ZM: 'Zâmbia',
  ZW: 'Zimbábue',
};

/**
 * Gets country name from UN/LOCODE (first 2 chars = ISO 3166-1 alpha-2).
 * Returns the country name if found, or undefined.
 */
export function getCountryFromCode(code: string): string | undefined {
  if (!code || code.length < 2) return undefined;
  const countryCode = code.slice(0, 2).toUpperCase();
  return COUNTRY_CODE_TO_NAME[countryCode];
}
